
/**
 * @fileOverview AI-powered moderation and categorization flow for FlixTrend.
 * This single flow analyzes content for safety and assigns it a category.
 */

import { ai, SafetyPolicy } from '@/ai/ai';
import { z } from 'zod';

const postCategories = [
    'Art & Design > 3D Modeling',
    'Art & Design > Animation',
    'Art & Design > Anime & Manga',
    'Art & Design > Architecture',
    'Art & Design > Art History',
    'Art & Design > Body Art & Tattoos',
    'Art & Design > Calligraphy & Lettering',
    'Art & Design > Ceramics & Pottery',
    'Art & Design > Comics & Graphic Novels',
    'Art & Design > Conceptual Art',
    'Art & Design > Crafts > Candle Making',
    'Art & Design > Crafts > Doll Making',
    'Art & Design > Crafts > Knitting & Crochet',
    'Art & Design > Crafts > Origami',
    'Art & Design > Crafts > Scrapbooking',
    'Art & Design > Crafts > Woodworking',
    'Art & Design > Digital Art',
    'Art & Design > Drawing & Sketching',
    'Art & Design > Fashion Design',
    'Art & Design > Fine Art',
    'Art & Design > Furniture Design',
    'Art & Design > Glassblowing',
    'Art & Design > Graffiti & Street Art',
    'Art & Design > Graphic Design',
    'Art & Design > Illustration',
    'Art & Design > Industrial Design',
    'Art & Design > Interior Design',
    'Art & Design > Jewelry Design',
    'Art & Design > Land Art',
    'Art & Design > Mixed Media',
    'Art & Design > Painting',
    'Art & Design > Photography > Abstract',
    'Art & Design > Photography > Aerial',
    'Art & Design > Photography > Astrophotography',
    'Art & Design > Photography > Black & White',
    'Art & Design > Photography > Commercial',
    'Art & Design > Photography > Documentary',
    'Art & Design > Photography > Drone',
    'Art & Design > Photography > Fashion',
    'Art & Design > Photography > Film',
    'Art & Design > Photography > Food',
    'Art & Design > Photography > Landscape',
    'Art & Design > Photography > Macro',
    'Art & Design > Photography > Mobile',
    'Art & Design > Photography > Nature',
    'Art & Design > Photography > Night',
    'Art & Design > Photography > People & Portraits',
    'Art & Design > Photography > Photojournalism',
    'Art & Design > Photography > Sports',
    'Art & Design > Photography > Still Life',
    'Art & Design > Photography > Street',
    'Art & Design > Photography > Travel',
    'Art & Design > Photography > Underwater',
    'Art & Design > Photography > Urban Exploration',
    'Art & Design > Printmaking',
    'Art & Design > Sculpture',
    'Art & Design > Storyboarding',
    'Art & Design > Textiles & Weaving',
    'Art & Design > Typography',
    'Art & Design > UI/UX Design',
    'Art & Design > Visual Arts',
    'Beauty & Fashion > Accessories',
    'Beauty & Fashion > Body Positivity',
    'Beauty & Fashion > Cosmetics & Makeup',
    'Beauty & Fashion > Fragrance',
    'Beauty & Fashion > Hair Care & Styling',
    'Beauty & Fashion > Haute Couture',
    'Beauty & Fashion > Luxury Brands',
    'Beauty & Fashion > Mens Fashion',
    'Beauty & Fashion > Modeling',
    'Beauty & Fashion > Nail Art',
    'Beauty & Fashion > Plus-Size Fashion',
    'Beauty & Fashion > Shopping & Hauls',
    'Beauty & Fashion > Skincare',
    'Beauty & Fashion > Streetwear & Sneakers',
    'Beauty & Fashion > Sustainable Fashion',
    'Beauty & Fashion > Thrifting & Vintage',
    'Beauty & Fashion > Womens Fashion',
    'Books & Literature > Audiobooks',
    'Books & Literature > Biographies & Memoirs',
    'Books & Literature > Book Clubs',
    'Books & Literature > Book Reviews',
    'Books & Literature > Childrens Books',
    'Books & Literature > Classical Literature',
    'Books & Literature > Creative Writing & Prompts',
    'Books & Literature > Fandom & Fan Fiction',
    'Books & Literature > Fantasy',
    'Books & Literature > Fiction',
    'Books & Literature > Historical Fiction',
    'Books & Literature > Horror',
    'Books & Literature > Literary Criticism',
    'Books & Literature > Mystery & Thriller',
    'Books & Literature > Non-Fiction',
    'Books & Literature > Poetry',
    'Books & Literature > Publishing',
    'Books & Literature > Romance',
    'Books & Literature > Science Fiction',
    'Books & Literature > Self-Help & Personal Growth',
    'Books & Literature > Writing & Authoring',
    'Books & Literature > Young Adult',
    'Business & Finance > Accounting',
    'Business & Finance > Advertising',
    'Business & Finance > Angel Investing',
    'Business & Finance > Banking',
    'Business & Finance > Business Law',
    'Business & Finance > Business Strategy',
    'Business & Finance > Career Development',
    'Business & Finance > Commodities',
    'Business & Finance > Corporate Culture',
    'Business & Finance > Crowdfunding',
    'Business & Finance > Customer Service',
    'Business & Finance > Data & Analytics',
    'Business & Finance > Economics',
    'Business & Finance > E-commerce',
    'Business & Finance > Entrepreneurship',
    'Business & Finance > Frugal Living & Budgeting',
    'Business & Finance > Human Resources',
    'Business & Finance > Insurance',
    'Business & Finance > International Business',
    'Business & Finance > Investing > Cryptocurrency',
    'Business & Finance > Investing > Day Trading',
    'Business & Finance > Investing > Forex',
    'Business & Finance > Investing > Futures & Options',
    'Business & Finance > Investing > Real Estate',
    'Business & Finance > Investing > Stocks & Bonds',
    'Business & Finance > Investing > Value Investing',
    'Business & Finance > Leadership & Management',
    'Business & Finance > Local Business',
    'Business & Finance > Logistics & Supply Chain',
    'Business & Finance > Marketing > Content Marketing',
    'Business & Finance > Marketing > Digital Marketing',
    'Business & Finance > Marketing > SEO',
    'Business & Finance > Marketing > Social Media Marketing',
    'Business & Finance > Mergers & Acquisitions',
    'Business & Finance > Non-profits & NGOs',
    'Business & Finance > Personal Finance',
    'Business & Finance > Project Management',
    'Business & Finance > Public Relations',
    'Business & Finance > Real Estate',
    'Business & Finance > Recruiting',
    'Business & Finance > Retail',
    'Business & Finance > Sales',
    'Business & Finance > Small Business',
    'Business & Finance > Startups',
    'Business & Finance > Taxes',
    'Business & Finance > Venture Capital',
    'Careers & Education > Admissions & Applications',
    'Careers & Education > Alumni Networks',
    'Careers & Education > Campus Life',
    'Careers & Education > Career Advice',
    'Careers & Education > Continuing Education',
    'Careers & Education > Distance Learning',
    'Careers & Education > Early Childhood Education',
    'Careers & Education > EdTech',
    'Careers & Education > Higher Education (College/University)',
    'Careers & Education > Homeschooling',
    'Careers & Education > Internships',
    'Careers & Education > Job Search & Interviewing',
    'Careers & Education > K-12 Education',
    'Careers & Education > Language Learning',
    'Careers & Education > Networking',
    'Careers & Education > Online Courses (MOOCs)',
    'Careers & Education > Resume & CV Building',
    'Careers & Education > Scholarships & Financial Aid',
    'Careers & Education > Special Education',
    'Careers & Education > Standardized Tests (SAT, GRE, etc.)',
    'Careers & Education > STEM Education',
    'Careers & Education > Study Abroad',
    'Careers & Education > Study Tips & Habits',
    'Careers & Education > Teacher Resources',
    'Careers & Education > Tutoring',
    'Careers & Education > Vocational & Trade School',
    'Events & Lifestyle > Activism & Causes',
    'Events & Lifestyle > Astrology & Horoscopes',
    'Events & Lifestyle > Awards & Ceremonies',
    'Events & Lifestyle > Bars & Nightlife',
    'Events & Lifestyle > Birthdays & Anniversaries',
    'Events & Lifestyle > Charity & Fundraising',
    'Events & Lifestyle > Concerts & Music Festivals',
    'Events & Lifestyle > Conferences & Conventions',
    'Events & Lifestyle > Cosplay',
    'Events & Lifestyle > Cultural Events',
    'Events & Lifestyle > Dating & Relationships',
    'Events & Lifestyle > DIY & Home Improvement',
    'Events & Lifestyle > Fairs & Festivals',
    'Events & Lifestyle > Family & Parenting',
    'Events & Lifestyle > Film Festivals',
    'Events & Lifestyle > Gardening & Horticulture',
    'Events & Lifestyle > Holidays & Celebrations',
    'Events & Lifestyle > Home & Decor',
    'Events & Lifestyle > LGBTQ+',
    'Events & Lifestyle > Life Hacks',
    'Events & Lifestyle > Marriage & Weddings',
    'Events & Lifestyle > Minimalist Living',
    'Events & Lifestyle > Myers-Briggs & Personality Types',
    'Events & Lifestyle > Mythology & Folklore',
    'Events & Lifestyle > Paranormal & Unexplained',
    'Events & Lifestyle > Parties & Social Gatherings',
    'Events & Lifestyle > Performing Arts > Dance',
    'Events & Lifestyle > Performing Arts > Theatre',
    'Events & Lifestyle > Pets & Animals > Amphibians & Reptiles',
    'Events & Lifestyle > Pets & Animals > Animal Rescue & Welfare',
    'Events & Lifestyle > Pets & Animals > Birds',
    'Events & Lifestyle > Pets & Animals > Cats',
    'Events & Lifestyle > Pets & Animals > Dogs',
    'Events & Lifestyle > Pets & Animals > Exotic Pets',
    'Events & Lifestyle > Pets & Animals > Fish & Aquariums',
    'Events & Lifestyle > Pets & Animals > Horses',
    'Events & Lifestyle > Pets & Animals > Rodents & Small Mammals',
    'Events & Lifestyle > Pets & Animals > Veterinary Medicine',
    'Events & Lifestyle > Psychedelics & Exploration',
    'Events & Lifestyle > Religion & Spirituality > Agnosticism & Atheism',
    'Events & Lifestyle > Religion & Spirituality > Buddhism',
    'Events & Lifestyle > Religion & Spirituality > Christianity',
    'Events & Lifestyle > Religion & Spirituality > Hinduism',
    'Events & Lifestyle > Religion & Spirituality > Islam',
    'Events & Lifestyle > Religion & Spirituality > Judaism',
    'Events & Lifestyle > Religion & Spirituality > New Age & Spirituality',
    'Events & Lifestyle > Religion & Spirituality > Paganism',
    'Events & Lifestyle > Religion & Spirituality > Philosophy',
    'Events & Lifestyle > Religion & Spirituality > Sikhism',
    'Events & Lifestyle > Rural & Country Living',
    'Events & Lifestyle > Self-Sufficiency & Homesteading',
    'Events & Lifestyle > Social Issues',
    'Events & Lifestyle > Subcultures',
    'Events & Lifestyle > Sustainability & Zero Waste',
    'Events & Lifestyle > Urban Living',
    'Events & Lifestyle > Volunteering',
    'Food & Drink > Baking',
    'Food & Drink > Barbecuing & Grilling',
    'Food & Drink > Bartending & Cocktails',
    'Food & Drink > Beer',
    'Food & Drink > Beverages (Non-alcoholic)',
    'Food & Drink > Coffee & Tea',
    'Food & Drink > Cooking & Recipes > Desserts & Baking',
    'Food & Drink > Cooking & Recipes > Healthy & Diet',
    'Food & Drink > Cooking & Recipes > International Cuisine',
    'Food & Drink > Cooking & Recipes > Meal Prep',
    'Food & Drink > Cooking & Recipes > Quick & Easy Meals',
    'Food & Drink > Cooking & Recipes > Vegan',
    'Food & Drink > Cooking & Recipes > Vegetarian',
    'Food & Drink > Culinary Arts & Chefs',
    'Food & Drink > Fermentation',
    'Food & Drink > Fine Dining',
    'Food & Drink > Food History & Culture',
    'Food & Drink > Food Industry & Agriculture',
    'Food & Drink > Food Reviews',
    'Food & Drink > Food Science',
    'Food & Drink > Homebrewing',
    'Food & Drink > Molecular Gastronomy',
    'Food & Drink > Restaurants & Eateries',
    'Food & Drink > Spirits & Liquor',
    'Food & Drink > Street Food',
    'Food & Drink > Veganism & Plant-Based Diets',
    'Food & Drink > Vegetarianism',
    'Food & Drink > Wine & Viticulture',
    'Gaming > Action & Adventure',
    'Gaming > Arcade & Retro',
    'Gaming > Augmented Reality (AR) Games',
    'Gaming > Board & Tabletop Games',
    'Gaming > Card Games (TCGs, CCGs)',
    'Gaming > Casual Games',
    'Gaming > Cheats & Glitches',
    'Gaming > Competitive Gaming & Esports > Apex Legends',
    'Gaming > Competitive Gaming & Esports > Call of Duty',
    'Gaming > Competitive Gaming & Esports > Counter-Strike (CS:GO)',
    'Gaming > Competitive Gaming & Esports > Dota 2',
    'Gaming > Competitive Gaming & Esports > FIFA',
    'Gaming > Competitive Gaming & Esports > Fortnite',
    'Gaming > Competitive Gaming & Esports > League of Legends (LoL)',
    'Gaming > Competitive Gaming & Esports > Overwatch',
    'Gaming > Competitive Gaming & Esports > Rainbow Six Siege',
    'Gaming > Competitive Gaming & Esports > Rocket League',
    'Gaming > Competitive Gaming & Esports > Super Smash Bros.',
    'Gaming > Competitive Gaming & Esports > Valorant',
    'Gaming > Educational Games',
    'Gaming > Emulation',
    'Gaming > Fighting Games',
    'Gaming > First-Person Shooters (FPS)',
    'Gaming > Game Development',
    'Gaming > Game Streaming (Twitch, YouTube Gaming)',
    'Gaming > Gaming Hardware & Accessories',
    'Gaming > Gaming News & Reviews',
    'Gaming > Indie Games',
    'Gaming > Let’s Plays & Walkthroughs',
    'Gaming > Massively Multiplayer Online (MMO)',
    'Gaming > Mobile Gaming',
    'Gaming > Mods & Modding',
    'Gaming > Music & Rhythm Games',
    'Gaming > Nintendo',
    'Gaming > Open World Games',
    'Gaming > Party Games',
    'Gaming > PC Gaming',
    'Gaming > Platformer Games',
    'Gaming > Playstation',
    'Gaming > Puzzle Games',
    'Gaming > Racing Games',
    'Gaming > Role-Playing Games (RPG)',
    'Gaming > Simulation Games',
    'Gaming > Speedrunning',
    'Gaming > Sports Games',
    'Gaming > Strategy Games (RTS, TBS)',
    'Gaming > Survival & Horror',
    'Gaming > Virtual Reality (VR) Games',
    'Gaming > Xbox',
    'General',
    'Health & Wellness > Alternative Medicine',
    'Health & Wellness > Anatomy & Physiology',
    'Health & Wellness > Biohacking',
    'Health & Wellness > Body Positivity',
    'Health & Wellness > Bodybuilding',
    'Health & Wellness > Chronic Illness & Pain Management',
    'Health & Wellness > Dentistry & Oral Health',
    'Health & Wellness > Disabilities & Accessibility',
    'Health & Wellness > Diseases & Conditions',
    'Health & Wellness > Exercise & Fitness > Aerobics & Cardio',
    'Health & Wellness > Exercise & Fitness > Barre',
    'Health & Wellness > Exercise & Fitness > Calisthenics',
    'Health & Wellness > Exercise & Fitness > CrossFit',
    'Health & Wellness > Exercise & Fitness > Dance Fitness',
    'Health & Wellness > Exercise & Fitness > Gym & Workout',
    'Health & Wellness > Exercise & Fitness > HIIT',
    'Health & Wellness > Exercise & Fitness > Martial Arts',
    'Health & Wellness > Exercise & Fitness > Pilates',
    'Health & Wellness > Exercise & Fitness > Powerlifting',
    'Health & Wellness > Exercise & Fitness > Running & Marathon',
    'Health & Wellness > Exercise & Fitness > Sports Training',
    'Health & Wellness > Exercise & Fitness > Stretching & Flexibility',
    'Health & Wellness > Exercise & Fitness > Weightlifting',
    'Health & Wellness > Exercise & Fitness > Yoga',
    'Health & Wellness > First Aid & Emergency Response',
    'Health & Wellness > Gerontology & Aging',
    'Health & Wellness > Medical Devices & Technology',
    'Health & Wellness > Medical Research',
    'Health & Wellness > Mens Health',
    'Health & Wellness > Mental Health > Addiction & Recovery',
    'Health & Wellness > Mental Health > Anxiety & Depression',
    'Health & Wellness > Mental Health > Bipolar Disorder',
    'Health & Wellness > Mental Health > Cognitive Behavioral Therapy (CBT)',
    'Health & Wellness > Mental Health > Mindfulness & Meditation',
    'Health & Wellness > Mental Health > Psychiatry',
    'Health & Wellness > Mental Health > Psychology',
    'Health & Wellness > Mental Health > Self-Care',
    'Health & Wellness > Mental Health > Therapy & Counseling',
    'Health & Wellness > Mental Health > Trauma & PTSD',
    'Health & Wellness > Neuroscience',
    'Health & Wellness > Nutrition & Dieting',
    'Health & Wellness > Pediatrics',
    'Health & Wellness > Pharmacy & Pharmacology',
    'Health & Wellness > Public Health',
    'Health & Wellness > Sleep Science',
    'Health & Wellness > Substance Abuse & Recovery',
    'Health & Wellness > Supplements',
    'Health & Wellness > Womens Health',
    'Hobbies & Interests > 3D Printing',
    'Hobbies & Interests > Antiquing & Collecting',
    'Hobbies & Interests > Astronomy & Stargazing',
    'Hobbies & Interests > Backpacking & Hiking',
    'Hobbies & Interests > Birdwatching',
    'Hobbies & Interests > Boating & Sailing',
    'Hobbies & Interests > Camping & Outdoors',
    'Hobbies & Interests > Canoeing & Kayaking',
    'Hobbies & Interests > Cars & Automotive > Car Customization & Tuning',
    'Hobbies & Interests > Cars & Automotive > Classic Cars',
    'Hobbies & Interests > Cars & Automotive > Electric Vehicles',
    'Hobbies & Interests > Cars & Automotive > Motorsports (F1, NASCAR, IndyCar)',
    'Hobbies & Interests > Cars & Automotive > Off-roading & 4x4',
    'Hobbies & Interests > Cars & Automotive > Supercars & Hypercars',
    'Hobbies & Interests > Chess',
    'Hobbies & Interests > Coin Collecting',
    'Hobbies & Interests > Couponing',
    'Hobbies & Interests > Drones & RC Vehicles',
    'Hobbies & Interests > Electronics & Gadgets',
    'Hobbies & Interests > Extreme Sports',
    'Hobbies & Interests > Fishing',
    'Hobbies & Interests > Foraging',
    'Hobbies & Interests > Genealogy',
    'Hobbies & Interests > Geocaching',
    'Hobbies & Interests > Home Automation',
    'Hobbies & Interests > Hunting',
    'Hobbies & Interests > Knitting & Crochet',
    'Hobbies & Interests > Lockpicking',
    'Hobbies & Interests > Magic & Illusion',
    'Hobbies & Interests > Metal Detecting',
    'Hobbies & Interests > Model Building (Cars, Planes, etc.)',
    'Hobbies & Interests > Motorcycling',
    'Hobbies & Interests > Parkour & Freerunning',
    'Hobbies & Interests > Pen & Paper RPGs (D&D)',
    'Hobbies & Interests > Poker & Card Games',
    'Hobbies & Interests > Quilting',
    'Hobbies & Interests > Radio & Ham Radio',
    'Hobbies & Interests > Scrapbooking',
    'Hobbies & Interests > Scuba Diving & Snorkeling',
    'Hobbies & Interests > Sewing',
    'Hobbies & Interests > Skateboarding & Longboarding',
    'Hobbies & Interests > Skiing & Snowboarding',
    'Hobbies & Interests > Stamp Collecting',
    'Hobbies & Interests > Surfing',
    'Hobbies & Interests > Survivalism & Prepping',
    'Hobbies & Interests > Train Spotting & Model Trains',
    'Hobbies & Interests > Traveling',
    'Hobbies & Interests > Urban Exploration',
    'Hobbies & Interests > Woodworking',
    'Movies & Television > Action & Adventure',
    'Movies & Television > Animation',
    'Movies & Television > Anime',
    'Movies & Television > Celebrities & Film Industry',
    'Movies & Television > Comedy',
    'Movies & Television > Cult Films',
    'Movies & Television > Documentaries',
    'Movies & Television > Drama',
    'Movies & Television > Film & TV Analysis',
    'Movies & Television > Film & TV History',
    'Movies & Television > Film & TV Production',
    'Movies & Television > Film & TV Reviews',
    'Movies & Television > Game Shows',
    'Movies & Television > Horror',
    'Movies & Television > Independent Film',
    'Movies & Television > Musicals',
    'Movies & Television > Mystery & Crime',
    'Movies & Television > Reality TV',
    'Movies & Television > Romance',
    'Movies & Television > Science Fiction & Fantasy',
    'Movies & Television > Sitcoms',
    'Movies & Television > Soap Operas & Telenovelas',
    'Movies & Television > Streaming Services (Netflix, Hulu, etc.)',
    'Movies & Television > Talk Shows',
    'Movies & Television > TV Series & Shows',
    'Movies & Television > Voice Acting',
    'Music > A Cappella',
    'Music > Afrobeats',
    'Music > Ambient',
    'Music > Americana & Folk',
    'Music > Bluegrass',
    'Music > Blues',
    'Music > Bollywood & Indian Pop',
    'Music > Chiptune',
    'Music > Choral',
    'Music > Christian & Gospel',
    'Music > Classical',
    'Music > Country',
    'Music > Cover Songs',
    'Music > Dance & Electronic',
    'Music > Disco',
    'Music > Drum and Bass',
    'Music > Dubstep',
    'Music > EDM',
    'Music > Emo',
    'Music > Funk',
    'Music > Grunge',
    'Music > Hardcore',
    'Music > Heavy Metal',
    'Music > Hip Hop & Rap',
    'Music > House',
    'Music > Indie & Alternative',
    'Music > Industrial',
    'Music > Instrumental',
    'Music > J-Pop',
    'Music > Jazz',
    'Music > K-Pop',
    'Music > Latin',
    'Music > Lo-fi',
    'Music > Marching Bands',
    'Music > Music Composition & Theory',
    'Music > Music Festivals',
    'Music > Music History',
    'Music > Music Industry',
    'Music > Music Production & DJing',
    'Music > Music Videos',
    'Music > Musical Instruments > Brass',
    'Music > Musical Instruments > Drums & Percussion',
    'Music > Musical Instruments > Guitar & Bass',
    'Music > Musical Instruments > Keyboard & Piano',
    'Music > Musical Instruments > Strings',
    'Music > Musical Instruments > Woodwinds',
    'Music > Musicals & Show Tunes',
    'Music > New Wave',
    'Music > Opera',
    'Music > Parody & Comedy Music',
    'Music > Pop',
    'Music > Psychedelic Rock',
    'Music > Punk',
    'Music > R&B & Soul',
    'Music > Reggae & Dancehall',
    'Music > Rock',
    'Music > Ska',
    'Music > Synthwave',
    'Music > Techno',
    'Music > Trance',
    'Music > Trap',
    'Music > Turntablism',
    'Music > Vaporwave',
    'Music > World Music',
    'News & Politics > Activism & Protests',
    'News & Politics > Conservative Politics',
    'News & Politics > Conspiracies',
    'News & Politics > Elections',
    'News & Politics > Environmental Issues',
    'News & Politics > Fact-Checking & Media Literacy',
    'News & Politics > Geopolitics',
    'News & Politics > Government & Public Administration',
    'News & Politics > Human Rights',
    'News & Politics > International News',
    'News & Politics > Investigative Journalism',
    'News & Politics > Law & Legal System',
    'News & Politics > Leftist & Progressive Politics',
    'News & Politics > Libertarian Politics',
    'News & Politics > Local News',
    'News & Politics > Military & Defense',
    'News & Politics > Political Cartoons & Satire',
    'News & Politics > Political Commentary',
    'News & Politics > Political History',
    'News & Politics > Political Scandals',
    'News & Politics > Political Science',
    'News & Politics > Social Justice',
    'News & Politics > True Crime',
    'News & Politics > US Politics',
    'News & Politics > World News',
    'Podcasts & Radio > Comedy Podcasts',
    'Podcasts & Radio > Educational Podcasts',
    'Podcasts & Radio > News & Politics Podcasts',
    'Podcasts & Radio > Radio Broadcasting',
    'Podcasts & Radio > Society & Culture Podcasts',
    'Podcasts & Radio > Sports Podcasts',
    'Podcasts & Radio > Storytelling Podcasts',
    'Podcasts & Radio > Technology Podcasts',
    'Podcasts & Radio > True Crime Podcasts',
    'Science & Technology > Aerospace & Aviation',
    'Science & Technology > Agriculture & AgTech',
    'Science & Technology > Anthropology',
    'Science & Technology > Archaeology',
    'Science & Technology > Artificial Intelligence > AI Art & Music',
    'Science & Technology > Artificial Intelligence > AI Ethics',
    'Science & Technology > Artificial Intelligence > Large Language Models (LLMs)',
    'Science & Technology > Artificial Intelligence > Machine Learning',
    'Science & Technology > Artificial Intelligence > Natural Language Processing (NLP)',
    'Science & Technology > Astronomy & Space Exploration',
    'Science & Technology > Augmented & Virtual Reality (AR/VR)',
    'Science & Technology > Automation & Robotics',
    'Science & Technology > Big Data',
    'Science & Technology > Bioinformatics',
    'Science & Technology > Biology',
    'Science & Technology > Biotechnology',
    'Science & Technology > Blockchain & Web3',
    'Science & Technology > Chemistry',
    'Science & Technology > Citizen Science',
    'Science & Technology > Climate Science',
    'Science & Technology > Cloud Computing',
    'Science & Technology > Cognitive Science',
    'Science & Technology > Computer Hardware > Custom PCs & Modding',
    'Science & Technology > Computer Hardware > CPUs & GPUs',
    'Science & Technology > Computer Hardware > Keyboards & Peripherals',
    'Science & Technology > Computer Science',
    'Science & Technology > Cybersecurity & Hacking',
    'Science & Technology > Data Science',
    'Science & Technology > Earth Sciences (Geology, Oceanography)',
    'Science & Technology > Ecology & Conservation',
    'Science & Technology > Electrical Engineering',
    'Science & Technology > Energy & Renewables',
    'Science & Technology > Engineering (General)',
    'Science & Technology > Environmental Science',
    'Science & Technology > Forensics',
    'Science & Technology > Futurism & Transhumanism',
    'Science & Technology > Genetics & Genomics',
    'Science & Technology > GIS & Cartography',
    'Science & Technology > History of Science & Tech',
    'Science & Technology > Information Technology (IT)',
    'Science & Technology > Internet Culture & Memes',
    'Science & Technology > Internet of Things (IoT)',
    'Science & Technology > Linguistics',
    'Science & Technology > Materials Science',
    'Science & Technology > Mathematics',
    'Science & Technology > Mechanical Engineering',
    'Science & Technology > Memes & Internet Culture',
    'Science & Technology > Mobile Development (iOS, Android)',
    'Science & Technology > Nanotechnology',
    'Science & Technology > Neuroscience',
    'Science & Technology > Open Source',
    'Science & Technology > Paleontology',
    'Science & Technology > Physics',
    'Science & Technology > Privacy & Encryption',
    'Science & Technology > Product & Industrial Design',
    'Science & Technology > Programming & Software Development > Agile & Scrum',
    'Science & Technology > Programming & Software Development > Algorithms & Data Structures',
    'Science & Technology > Programming & Software Development > APIs & Microservices',
    'Science & Technology > Programming & Software Development > Assembly',
    'Science & Technology > Programming & Software Development > C & C++',
    'Science & Technology > Programming & Software Development > C# & .NET',
    'Science & Technology > Programming & Software Development > Clojure',
    'Science & Technology > Programming & Software Development > Compilers & Interpreters',
    'Science & Technology > Programming & Software Development > Dart',
    'Science & Technology > Programming & Software Development > DevOps',
    'Science & Technology > Programming & Software Development > Elixir',
    'Science & Technology > Programming & Software Development > F#',
    'Science & Technology > Programming & Software Development > Functional Programming',
    'Science & Technology > Programming & Software Development > Go (Golang)',
    'Science & Technology > Programming & Software Development > Haskell',
    'Science & Technology > Programming & Software Development > Java',
    'Science & Technology > Programming & Software Development > JavaScript & TypeScript',
    'Science & Technology > Programming & Software Development > Julia',
    'Science & Technology > Programming & Software Development > Kotlin',
    'Science & Technology > Programming & Software Development > Lisp',
    'Science & Technology > Programming & Software Development > Lua',
    'Science & Technology > Programming & Software Development > No-Code & Low-Code',
    'Science & Technology > Programming & Software Development > Objective-C',
    'Science & Technology > Programming & Software Development > Perl',
    'Science & Technology > Programming & Software Development > PHP',
    'Science & Technology > Programming & Software Development > Python',
    'Science & Technology > Programming & Software Development > R',
    'Science & Technology > Programming & Software Development > Ruby',
    'Science & Technology > Programming & Software Development > Rust',
    'Science & Technology > Programming & SoftwareDevelopment > Scala',
    'Science & Technology > Programming & Software Development > Shell Scripting',
    'Science & Technology > Programming & Software Development > SQL',
    'Science & Technology > Programming & Software Development > Swift & iOS Development',
    'Science & Technology > Programming & Software Development > VBA',
    'Science & Technology > Programming & Software Development > Web Development > Angular',
    'Science & Technology > Programming & Software Development > Web Development > Backend',
    'Science & Technology > Programming & Software Development > Web Development > CSS & Frameworks',
    'Science & Technology > Programming & Software Development > Web Development > Frontend & React',
    'Science & Technology > Programming & Software Development > Web Development > HTML5',
    'Science & Technology > Programming & Software Development > Web Development > Svelte',
    'Science & Technology > Programming & Software Development > Web Development > Vue',
    'Science & Technology > Quantum Computing',
    'Science & Technology > Science Communication',
    'Science & Technology > Social Media & Platforms',
    'Science & Technology > Sociology',
    'Science & Technology > Space Technology',
    'Science & Technology > Startups & Tech Industry',
    'Science & Technology > Transportation Tech',
    'Science & Technology > Video & Audio Technology',
    'Science & Technology > Wearable Tech',
    'Science & Technology > Zoology',
    'Sports > Action Sports',
    'Sports > American Football (NFL)',
    'Sports > Archery',
    'Sports > Australian Rules Football',
    'Sports > Badminton',
    'Sports > Baseball (MLB)',
    'Sports > Basketball (NBA)',
    'Sports > Billiards & Pool',
    'Sports > Bodybuilding & Fitness Competitions',
    'Sports > Bowling',
    'Sports > Boxing',
    'Sports > Cheerleading',
    'Sports > Climbing',
    'Sports > Cricket',
    'Sports > Curling',
    'Sports > Cycling',
    'Sports > Darts',
    'Sports > Disc Golf',
    'Sports > Diving',
    'Sports > Dodgeball',
    'Sports > Equestrian',
    'Sports > Fencing',
    'Sports > Fantasy Sports',
    'Sports > Field Hockey',
    'Sports > Figure Skating',
    'Sports > Fishing',
    'Sports > Golf',
    'Sports > Gymnastics',
    'Sports > Handball',
    'Sports > Hockey (NHL)',
    'Sports > Horse Racing',
    'Sports > Lacrosse',
    'Sports > Martial Arts (MMA, UFC)',
    'Sports > Olympics',
    'Sports > Paintball & Airsoft',
    'Sports > Paralympics',
    'Sports > Pickleball',
    'Sports > Pro Wrestling (WWE, AEW)',
    'Sports > Racquetball',
    'Sports > Roller Derby',
    'Sports > Rowing',
    'Sports > Rugby',
    'Sports > Running & Track',
    'Sports > Sailing',
    'Sports > Skateboarding',
    'Sports > Skiing & Snowboarding',
    'Sports > Soccer (Football)',
    'Sports > Softball',
    'Sports > Sports Betting',
    'Sports > Sports Broadcasting & Journalism',
    'Sports > Sports History',
    'Sports > Sports Management & Business',
    'Sports > Sports Medicine',
    'Sports > Sports Psychology',
    'Sports > Squash',
    'Sports > Surfing',
    'Sports > Swimming',
    'Sports > Table Tennis',
    'Sports > Tennis',
    'Sports > Triathlon',
    'Sports > Ultimate Frisbee',
    'Sports > Volleyball',
    'Sports > Water Polo',
    'Sports > Weightlifting',
    'Sports > Winter Sports',
    'Sports > Wrestling',
    'Travel > Adventure Travel',
    'Travel > Beaches & Islands',
    'Travel > Budget Travel',
    'Travel > Business Travel',
    'Travel > City Guides',
    'Travel > Cruises',
    'Travel > Cultural Travel',
    'Travel > Digital Nomad Life',
    'Travel > Ecotourism',
    'Travel > Family Travel',
    'Travel > Food & Drink Travel',
    'Travel > Hiking & Backpacking',
    'Travel > Honeymoons & Romantic Getaways',
    'Travel > Hotels & Accommodation',
    'Travel > Luxury Travel',
    'Travel > National Parks',
    'Travel > Road Trips',
    'Travel > Solo Travel',
    'Travel > Space Travel',
    'Travel > Themed Travel (e.g. Disney)',
    'Travel > Travel Gear & Hacks',
    'Travel > Travel Vlogging',
    'Vehicles > Airplanes',
    'Vehicles > Boats & Ships',
    'Vehicles > Buses',
    'Vehicles > Cars',
    'Vehicles > Electric Vehicles',
    'Vehicles > Heavy Machinery',
    'Vehicles > Motorcycles',
    'Vehicles > Public Transport',
    'Vehicles > Recreational Vehicles (RVs)',
    'Vehicles > Trains',
    'Vehicles > Trucks',
].map(c => c as const);

const ContentModerationInputSchema = z.object({
  text: z.string().optional().describe('All text content combined (caption, title, etc.).'),
  media: z.array(z.object({ url: z.string() })).optional().describe("An array of media items (images, videos) as data URIs. This is currently ignored."),
});

const ContentModerationOutputSchema = z.object({
    analysis: z.string().describe("Your step-by-step reasoning for the safety decision. First, state if any rule is violated and why. If not, state that the content is compliant."),
    decision: z.enum(['approve', 'deny']).describe("Based ONLY on your analysis, decide whether to approve or deny. If your analysis found no clear violation, you MUST approve."),
    reason: z.string().describe("A brief, user-friendly explanation for the decision. If approved, say 'Content approved!'. If denied, explain the violation simply."),
    category: z.string().describe("The single best category for the post from the provided list. Base this on the main topic of the text content. It must be one of the provided categories. Avoid using 'Other' or 'Uncategorized' unless no other category is remotely suitable."),
});

const moderationPrompt = `You are an expert content classifier and a fair and balanced content moderator for a Gen-Z social media app called FlixTrend.
Your goal is to keep the platform safe while allowing for creative expression. You will ONLY analyze the text content provided.

**Your Task (Chain-of-Thought Process):**

**Step 1: Moderation Analysis**
Carefully review the text content against the rules below. In your 'analysis' field, write down your reasoning.
- If a rule is clearly and severely violated, state which rule and why.
- If no rules are violated, explicitly state "Content is compliant."

**Step 2: Moderation Decision**
Based ONLY on your analysis from Step 1, make your 'decision'.
- If your analysis identified a clear and severe violation, you MUST decide 'deny'.
- If your analysis concluded "Content is compliant", you MUST decide 'approve'.

**Step 3: Categorization**
Analyze the text content and assign it to the single most relevant category from the list below. In the 'category' field, provide only the category name from the list. Be specific. Avoid the 'General' category unless the content has no discernible topic whatsoever.
Categories: ${postCategories.join(', ')}

**Rules (Deny content ONLY for clear and severe violations of the TEXT):**
1. Harmful or Abusive: True hate speech, credible violent threats, harassment, bullying, promotion of self-harm.
2. Spam/Illegal: Promoting illegal acts, scams, or posting pure gibberish.

Be lenient. Do NOT flag edgy humor, slang, or mild profanity. If it's ambiguous, approve it.

**Content to Review:**
TEXT: "{{text}}"
`;

const noSafetyBlocks: SafetyPolicy[] = [
  { category: 'HARM_CATEGORY_DANGEROUS_CONTENT', threshold: 'BLOCK_NONE' },
  { category: 'HARM_CATEGORY_HARASSMENT', threshold: 'BLOCK_NONE' },
  { category: 'HARM_CATEGORY_HATE_SPEECH', threshold: 'BLOCK_NONE' },
  { category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT', threshold: 'BLOCK_NONE' },
];

export const contentModerationFlow = ai.defineFlow(
  {
    name: 'contentModerationFlow',
    inputSchema: ContentModerationInputSchema,
    outputSchema: ContentModerationOutputSchema,
  },
  async (input) => {
    // Media is now ignored. We only process text.
    const finalText = input.text || '';
    
    // If there is no text content to moderate, approve and categorize as 'General'.
    if (!finalText.trim()) {
        return {
            analysis: "No text content provided. Approved by default.",
            decision: 'approve',
            reason: 'Content approved!',
            category: 'General',
        }
    }

    const finalPrompt = moderationPrompt
      .replace('"{{text}}"', JSON.stringify(finalText));

    const response = await ai.generate({
      model: 'googleai/gemini-2.0-flash-lite-001',
      prompt: finalPrompt,
      output: { schema: ContentModerationOutputSchema },
      safetySettings: noSafetyBlocks,
      config: {
        temperature: 0.1,
      },
    });

    const output = response.output;
    if (!output) {
      console.error("Moderation flow failed to produce valid output.", response.usage);
      return {
        analysis: "AI model failed to produce a valid response.",
        decision: 'deny',
        reason: 'Could not verify content safety at this time. Please try again.',
        category: 'General', // Default category on failure
      };
    }
    
    // Validate that the returned category is in the list
    if (!postCategories.includes(output.category as any)) {
      console.warn(`AI returned an invalid category: '${output.category}'. Defaulting to 'General'.`);
      output.category = 'General';
    }


    return output;
  }
);

    