export const GENRES = [
  // Mainstream
  { value: "pop", label: "Pop" },
  { value: "rock", label: "Rock" },
  { value: "hip-hop", label: "Hip-Hop" },
  { value: "rap", label: "Rap" },
  { value: "r&b", label: "R&B" },
  { value: "edm", label: "EDM" },
  { value: "dance", label: "Dance" },
  { value: "indie", label: "Indie" },
  { value: "alternative", label: "Alternative" },
  { value: "classical", label: "Classical" },
  // Electronic
  { value: "house", label: "House" },
  { value: "techno", label: "Techno" },
  { value: "trance", label: "Trance" },
  { value: "dubstep", label: "Dubstep" },
  { value: "drum-and-bass", label: "Drum & Bass" },
  { value: "future-bass", label: "Future Bass" },
  { value: "electro-pop", label: "Electro Pop" },
  { value: "deep-house", label: "Deep House" },
  { value: "progressive-house", label: "Progressive House" },
  { value: "lo-fi", label: "Lo-fi" },
  // Rock Variants
  { value: "hard-rock", label: "Hard Rock" },
  { value: "punk-rock", label: "Punk Rock" },
  { value: "metal", label: "Metal" },
  { value: "heavy-metal", label: "Heavy Metal" },
  { value: "indie-rock", label: "Indie Rock" },
  { value: "alternative-rock", label: "Alternative Rock" },
  { value: "soft-rock", label: "Soft Rock" },
  { value: "grunge", label: "Grunge" },
  // Hip-Hop Variants
  { value: "trap", label: "Trap" },
  { value: "drill", label: "Drill" },
  { value: "boom-bap", label: "Boom Bap" },
  { value: "conscious-rap", label: "Conscious Rap" },
  { value: "desi-hip-hop", label: "Desi Hip-Hop" },
  // Soul / Smooth
  { value: "soul", label: "Soul" },
  { value: "jazz", label: "Jazz" },
  { value: "blues", label: "Blues" },
  { value: "funk", label: "Funk" },
  { value: "gospel", label: "Gospel" },
  // Indian Focus
  { value: "bollywood", label: "Bollywood" },
  { value: "punjabi", label: "Punjabi" },
  { value: "indie-indian", label: "Indie Indian" },
  { value: "bhajan", label: "Bhajan" },
  { value: "ghazal", label: "Ghazal" },
  { value: "sufi", label: "Sufi" },
  { value: "carnatic", label: "Carnatic" },
  { value: "hindustani-classical", label: "Hindustani Classical" },
  { value: "folk", label: "Folk" },
  // World
  { value: "latin", label: "Latin" },
  { value: "reggaeton", label: "Reggaeton" },
  { value: "afrobeat", label: "Afrobeat" },
  { value: "k-pop", label: "K-Pop" },
  { value: "j-pop", label: "J-Pop" },
  // Chill / Mood
  { value: "chillout", label: "Chillout" },
  { value: "ambient", label: "Ambient" },
  { value: "sad", label: "Sad" },
  { value: "romantic", label: "Romantic" },
  { value: "party", label: "Party" },
  { value: "workout", label: "Workout" },
  { value: "sleep", label: "Sleep" },
  { value: "acoustic", label: "Acoustic" },
];

export const LANGUAGES = [
  { value: "english", label: "English" },
  { value: "hindi", label: "Hindi" },
  { value: "punjabi", label: "Punjabi" },
  { value: "spanish", label: "Spanish" },
  { value: "french", label: "French" },
  { value: "german", label: "German" },
  { value: "korean", label: "Korean" },
  { value: "japanese", label: "Japanese" },
  { value: "marathi", label: "Marathi" },
  { value: "tamil", label: "Tamil" },
  { value: "telugu", label: "Telugu" },
];
