import { NextResponse } from 'next/server';

const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY || '',
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN || '',
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID || '',
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET || '',
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID || '',
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID || '',
};

const workerSource = [
  "importScripts('https://www.gstatic.com/firebasejs/12.6.0/firebase-app-compat.js');",
  "importScripts('https://www.gstatic.com/firebasejs/12.6.0/firebase-messaging-compat.js');",
  "",
  `firebase.initializeApp(${JSON.stringify(firebaseConfig)});`,
  "",
  "const messaging = firebase.messaging();",
  "",
  "messaging.onBackgroundMessage(function(payload) {",
  "  const notificationTitle = payload.notification?.title || 'FlixTrend';",
  "  const notificationOptions = {",
  "    body: payload.notification?.body || '',",
  "    icon: '/icons/icon-192x192.png',",
  "    data: payload.data || {},",
  "    tag: payload.data?.type ? 'flixtrend-' + payload.data.type : undefined,",
  "  };",
  "  self.registration.showNotification(notificationTitle, notificationOptions);",
  "});",
  "",
  "self.addEventListener('notificationclick', function(event) {",
  "  event.notification.close();",
  "  const data = event.notification?.data || {};",
  "  let url = '/';",
  "",
  "  if (data.link) {",
  "    url = data.link.startsWith('http') ? data.link : data.link;",
  "  } else ",
  "  if (data.type === 'message' && data.targetId) {",
  "    url = '/signal/' + data.targetId;",
  "  } else if (data.type === 'profile' && data.targetUsername) {",
  "    url = '/squad/' + data.targetUsername;",
  "  } else if (data.type === 'drop' && data.targetId) {",
  "    url = '/drop/' + data.targetId;",
  "  }",
  "",
  "  event.waitUntil(",
  "    clients.matchAll({ type: 'window', includeUncontrolled: true }).then(function(clientList) {",
  "      for (const client of clientList) {",
  "        if (client.url.startsWith(self.location.origin) && 'focus' in client) {",
  "          return client.focus().then(() => {",
  "            if ('navigate' in client) {",
  "              return client.navigate(url);",
  "            }",
  "            return null;",
  "          });",
  "        }",
  "      }",
  "      return clients.openWindow(url);",
  "    })",
  "  );",
  "});",
].join('\n');

export async function GET() {
  return new Response(workerSource, {
    headers: {
      'Content-Type': 'application/javascript',
    },
  });
}
