// A comprehensive list of categories for content classification.
// Total: 800+ categories
export const contentCategories = [
    'Art & Design > 3D Modeling',
    'Art & Design > Animation',
    'Art & Design > Anime & Manga',
    'Art & Design > Architecture',
    'Art & Design > Body Art & Tattoos',
    'Art & Design > Calligraphy & Lettering',
    'Art & Design > Ceramics & Pottery',
    'Art & Design > Comics & Graphic Novels',
    'Art & Design > Conceptual Art',
    'Art & Design > Crafts',
    'Art & Design > Digital Art',
    'Art & Design > Drawing & Sketching',
    'Art & Design > Fashion Design',
    'Art & Design > Fine Art',
    'Art & Design > Graffiti & Street Art',
    'Art & Design > Graphic Design',
    'Art & Design > Illustration',
    'Art & Design > Industrial Design',
    'Art & Design > Interior Design',
    'Art & Design > Jewelry Design',
    'Art & Design > Land Art',
    'Art & Design > Mixed Media',
    'Art & Design > Painting',
    'Art & Design > Photography > Abstract',
    'Art & Design > Photography > Aerial',
    'Art & Design > Photography > Astrophotography',
    'Art & Design > Photography > Black & White',
    'Art & Design > Photography > Commercial',
    'Art & Design > Photography > Documentary',
    'Art & Design > Photography > Drone',
    'Art & Design > Photography > Fashion',
    'Art & Design > Photography > Film',
    'Art & Design > Photography > Food',
    'Art & Design > Photography > Landscape',
    'Art & Design > Photography > Macro',
    'Art & Design > Photography > Mobile',
    'Art & Design > Photography > Nature',
    'Art & Design > Photography > Night',
    'Art & Design > Photography > People & Portraits',
    'Art & Design > Photography > Photojournalism',
    'Art & Design > Photography > Sports',
    'Art & Design > Photography > Still Life',
    'Art & Design > Photography > Street',
    'Art & Design > Photography > Travel',
    'Art & Design > Photography > Underwater',
    'Art & Design > Photography > Urban Exploration',
    'Art & Design > Printmaking',
    'Art & Design > Sculpture',
    'Art & Design > Storyboarding',
    'Art & Design > Textiles & Weaving',
    'Art & Design > Typography',
    'Art & Design > UI/UX Design',
    'Art & Design > Visual Arts',
    'Beauty & Fashion > Accessories',
    'Beauty & Fashion > Cosmetics & Makeup',
    'Beauty & Fashion > Fragrance',
    'Beauty & Fashion > Hair Care & Styling',
    'Beauty & Fashion > Haute Couture',
    'Beauty & Fashion > Luxury Brands',
    'Beauty & Fashion > Mens Fashion',
    'Beauty & Fashion > Modeling',
    'Beauty & Fashion > Nail Art',
    'Beauty & Fashion > Plus-Size Fashion',
    'Beauty & Fashion > Shopping & Hauls',
    'Beauty & Fashion > Skincare',
    'Beauty & Fashion > Streetwear & Sneakers',
    'Beauty & Fashion > Sustainable Fashion',
    'Beauty & Fashion > Thrifting & Vintage',
    'Beauty & Fashion > Womens Fashion',
    'Books & Literature > Audiobooks',
    'Books & Literature > Biographies & Memoirs',
    'Books & Literature > Book Clubs',
    'Books & Literature > Book Reviews',
    'Books & Literature > Childrens Books',
    'Books & Literature > Classical Literature',
    'Books & Literature > Creative Writing & Prompts',
    'Books & Literature > Fandom & Fan Fiction',
    'Books & Literature > Fantasy',
    'Books & Literature > Fiction',
    'Books & Literature > Historical Fiction',
    'Books & Literature > Horror',
    'Books & Literature > Mystery & Thriller',
    'Books & Literature > Non-Fiction',
    'Books & Literature > Poetry',
    'Books & Literature > Publishing',
    'Books & Literature > Romance',
    'Books & Literature > Science Fiction',
    'Books & Literature > Self-Help & Personal Growth',
    'Books & Literature > Writing & Authoring',
    'Books & Literature > Young Adult',
    'Business & Finance > Accounting',
    'Business & Finance > Advertising',
    'Business & Finance > Angel Investing',
    'Business & Finance > Banking',
    'Business & Finance > Business Law',
    'Business & Finance > Business Strategy',
    'Business & Finance > Career Development',
    'Business & Finance > Commodities',
    'Business & Finance > Corporate Culture',
    'Business & Finance > Crowdfunding',
    'Business & Finance > Customer Service',
    'Business & Finance > Data & Analytics',
    'Business & Finance > Economics',
    'Business & Finance > E-commerce',
    'Business & Finance > Entrepreneurship',
    'Business & Finance > Frugal Living & Budgeting',
    'Business & Finance > Human Resources',
    'Business & Finance > Insurance',
    'Business & Finance > International Business',
    'Business & Finance > Investing > Cryptocurrency',
    'Business & Finance > Investing > Day Trading',
    'Business & Finance > Investing > Forex',
    'Business & Finance > Investing > Futures & Options',
    'Business & Finance > Investing > Real Estate',
    'Business & Finance > Investing > Stocks & Bonds',
    'Business & Finance > Investing > Value Investing',
    'Business & Finance > Leadership & Management',
    'Business & Finance > Local Business',
    'Business & Finance > Logistics & Supply Chain',
    'Business & Finance > Marketing',
    'Business & Finance > Mergers & Acquisitions',
    'Business & Finance > Non-profits & NGOs',
    'Business & Finance > Personal Finance',
    'Business & Finance > Project Management',
    'Business & Finance > Public Relations',
    'Business & Finance > Real Estate',
    'Business & Finance > Recruiting',
    'Business & Finance > Retail',
    'Business & Finance > Sales',
    'Business & Finance > Small Business',
    'Business & Finance > Startups',
    'Business & Finance > Taxes',
    'Business & Finance > Venture Capital',
    'Careers & Education > Admissions & Applications',
    'Careers & Education > Alumni Networks',
    'Careers & Education > Campus Life',
    'Careers & Education > Career Advice',
    'Careers & Education > Continuing Education',
    'Careers & Education > Distance Learning',
    'Careers & Education > Early Childhood Education',
    'Careers & Education > EdTech',
    'Careers & Education > Higher Education (College/University)',
    'Careers & Education > Homeschooling',
    'Careers & Education > Internships',
    'Careers & Education > Job Search & Interviewing',
    'Careers & Education > K-12 Education',
    'Careers & Education > Language Learning',
    'Careers & Education > Networking',
    'Careers & Education > Online Courses (MOOCs)',
    'Careers & Education > Resume & CV Building',
    'Careers & Education > Scholarships & Financial Aid',
    'Careers & Education > Special Education',
    'Careers & Education > Standardized Tests (SAT, GRE, etc.)',
    'Careers & Education > Study Abroad',
    'Careers & Education > Study Tips & Habits',
    'Careers & Education > Tutoring',
    'Careers & Education > Vocational & Trade School',
    'Events & Lifestyle > Activism & Causes',
    'Events & Lifestyle > Astrology & Horoscopes',
    'Events & Lifestyle > Awards & Ceremonies',
    'Events & Lifestyle > Bars & Nightlife',
    'Events & Lifestyle > Birthdays & Anniversaries',
    'Events & Lifestyle > Charity & Fundraising',
    'Events & Lifestyle > Concerts & Music Festivals',
    'Events & Lifestyle > Conferences & Conventions',
    'Events & Lifestyle > Cosplay',
    'Events & Lifestyle > Cultural Events',
    'Events & Lifestyle > Dating & Relationships',
    'Events & Lifestyle > DIY & Home Improvement',
    'Events & Lifestyle > Fairs & Festivals',
s    'Events & Lifestyle > Family & Parenting',
    'Events & Lifestyle > Film Festivals',
    'Events & Lifestyle > Gardening & Horticulture',
    'Events & Lifestyle > Holidays & Celebrations',
    'Events & Lifestyle > Home & Decor',
    'Events & Lifestyle > LGBTQ+',
    'Events & Lifestyle > Life Hacks',
    'Events & Lifestyle > Marriage & Weddings',
    'Events & Lifestyle > Minimalist Living',
    'Events & Lifestyle > Myers-Briggs & Personality Types',
    'Events & Lifestyle > Mythology & Folklore',
    'Events & Lifestyle > Paranormal & Unexplained',
    'Events & Lifestyle > Parties & Social Gatherings',
    'Events & Lifestyle > Performing Arts (Theatre, Dance)',
    'Events & Lifestyle > Pets & Animals > Amphibians & Reptiles',
    'Events & Lifestyle > Pets & Animals > Animal Rescue & Welfare',
    'Events & Lifestyle > Pets & Animals > Birds',
    'Events & Lifestyle > Pets & Animals > Cats',
    'Events & Lifestyle > Pets & Animals > Dogs',
    'Events & Lifestyle > Pets & Animals > Exotic Pets',
    'Events & Lifestyle > Pets & Animals > Fish & Aquariums',
    'Events & Lifestyle > Pets & Animals > Horses',
    'Events & Lifestyle > Pets & Animals > Rodents & Small Mammals',
    'Events & Lifestyle > Pets & Animals > Veterinary Medicine',
    'Events & Lifestyle > Psychedelics & Exploration',
    'Events & Lifestyle > Religion & Spirituality > Agnosticism & Atheism',
    'Events & Lifestyle > Religion & Spirituality > Buddhism',
    'Events & Lifestyle > Religion & Spirituality > Christianity',
    'Events & Lifestyle > Religion & Spirituality > Hinduism',
    'Events & Lifestyle > Religion & Spirituality > Islam',
    'Events & Lifestyle > Religion & Spirituality > Judaism',
    'Events & Lifestyle > Religion & Spirituality > New Age & Spirituality',
    'Events & Lifestyle > Religion & Spirituality > Philosophy',
    'Events & Lifestyle > Religion & Spirituality > Sikhism',
    'Events & Lifestyle > Rural & Country Living',
    'Events & Lifestyle > Self-Sufficiency & Homesteading',
    'Events & Lifestyle > Social Issues',
    'Events & Lifestyle > Subcultures',
    'Events & Lifestyle > Urban Living',
    'Events & Lifestyle > Volunteering',
    'Food & Drink > Baking',
    'Food & Drink > Barbecuing & Grilling',
    'Food & Drink > Bartending & Cocktails',
    'Food & Drink > Beer',
    'Food & Drink > Beverages (Non-alcoholic)',
    'Food & Drink > Coffee & Tea',
    'Food & Drink > Cooking & Recipes > Desserts & Baking',
    'Food & Drink > Cooking & Recipes > Healthy & Diet',
    'Food & Drink > Cooking & Recipes > International Cuisine',
    'Food & Drink > Cooking & Recipes > Quick & Easy Meals',
    'Food & Drink > Cooking & Recipes > Vegan',
    'Food & Drink > Cooking & Recipes > Vegetarian',
    'Food & Drink > Culinary Arts & Chefs',
    'Food & Drink > Fine Dining',
    'Food & Drink > Food History & Culture',
    'Food & Drink > Food Industry & Agriculture',
    'Food & Drink > Food Reviews',
    'Food & Drink > Food Science',
    'Food & Drink > Homebrewing',
h    'Food & Drink > Meal Prep',
    'Food & Drink > Molecular Gastronomy',
    'Food & Drink > Restaurants & Eateries',
s    'Food & Drink > Spirits & Liquor',
    'Food & Drink > Street Food',
    'Food & Drink > Veganism & Plant-Based Diets',
    'Food & Drink > Vegetarianism',
    'Food & Drink > Wine & Viticulture',
    'Gaming > Action & Adventure',
    'Gaming > Arcade & Retro',
    'Gaming > Augmented Reality (AR) Games',
    'Gaming > Board & Tabletop Games',
    'Gaming > Card Games (TCGs, CCGs)',
    'Gaming > Casual Games',
    'Gaming > Cheats & Glitches',
    'Gaming > Competitive Gaming & Esports > Call of Duty',
    'Gaming > Competitive Gaming & Esports > Counter-Strike (CS:GO)',
    'Gaming > Competitive Gaming & Esports > Dota 2',
    'Gaming > Competitive Gaming & Esports > League of Legends (LoL)',
    'Gaming > Competitive Gaming & Esports > Overwatch',
    'Gaming > Competitive Gaming & Esports > Rocket League',
    'Gaming > Competitive Gaming & Esports > Super Smash Bros.',
    'Gaming > Competitive Gaming & Esports > Valorant',
    'Gaming > Educational Games',
    'Gaming > Emulation',
    'Gaming > Fighting Games',
    'Gaming > First-Person Shooters (FPS)',
    'Gaming > Game Development',
    'Gaming > Game Streaming (Twitch, YouTube Gaming)',
    'Gaming > Gaming Hardware & Accessories',
    'Gaming > Gaming News & Reviews',
    'Gaming > Indie Games',
    'Gaming > Let’s Plays & Walkthroughs',
    'Gaming > Massively Multiplayer Online (MMO)',
    'Gaming > Mobile Gaming',
    'Gaming > Mods & Modding',
    'Gaming > Music & Rhythm Games',
    'Gaming > Open World Games',
    'Gaming > Party Games',
    'Gaming > PC Gaming',
    'Gaming > Platformer Games',
    'Gaming > Playstation',
    'Gaming > Puzzle Games',
    'Gaming > Racing Games',
    'Gaming > Role-Playing Games (RPG)',
    'Gaming > Simulation Games',
    'Gaming > Speedrunning',
    'Gaming > Sports Games',
    'Gaming > Strategy Games (RTS, TBS)',
    'Gaming > Survival & Horror',
    'Gaming > Virtual Reality (VR) Games',
    'Gaming > Xbox',
    'General',
    'Health & Wellness > Alternative Medicine',
    'Health & Wellness > Anatomy & Physiology',
    'Health & Wellness > Biohacking',
    'Health & Wellness > Body Positivity',
    'Health & Wellness > Bodybuilding',
    'Health & Wellness > Chronic Illness & Pain Management',
    'Health & Wellness > Dentistry & Oral Health',
    'Health & Wellness > Disabilities & Accessibility',
    'Health & Wellness > Diseases & Conditions',
    'Health & Wellness > Exercise & Fitness > Aerobics & Cardio',
    'Health & Wellness > Exercise & Fitness > Calisthenics',
    'Health & Wellness > Exercise & Fitness > CrossFit',
    'Health & Wellness > Exercise & Fitness > Gym & Workout',
    'Health & Wellness > Exercise & Fitness > HIIT',
    'Health & Wellness > Exercise & Fitness > Martial Arts',
    'Health & Wellness > Exercise & Fitness > Pilates',
    'Health & Wellness > Exercise & Fitness > Powerlifting',
    'Health & Wellness > Exercise & Fitness > Running & Marathon',
    'Health & Wellness > Exercise & Fitness > Sports Training',
    'Health & Wellness > Exercise & Fitness > Weightlifting',
    'Health & Wellness > Exercise & Fitness > Yoga',
    'Health & Wellness > First Aid & Emergency Response',
    'Health & Wellness > Gerontology & Aging',
    'Health & Wellness > Medical Devices & Technology',
    'Health & Wellness > Medical Research',
s    'Health & Wellness > Mens Health',
    'Health & Wellness > Mental Health > Addiction & Recovery',
    'Health & Wellness > Mental Health > Anxiety & Depression',
    'Health & Wellness > Mental Health > Mindfulness & Meditation',
    'Health & Wellness > Mental Health > Psychiatry',
    'Health & Wellness > Mental Health > Psychology',
    'Health & Wellness > Mental Health > Self-Care',
    'Health & Wellness > Mental Health > Therapy & Counseling',
    'Health & Wellness > Mental Health > Trauma & PTSD',
    'Health & Wellness > Neuroscience',
    'Health & Wellness > Nutrition & Dieting',
    'Health & Wellness > Pediatrics',
    'Health & Wellness > Pharmacy & Pharmacology',
    'Health & Wellness > Public Health',
    'Health & Wellness > Sleep Science',
    'Health & Wellness > Substance Abuse & Recovery',
    'Health & Wellness > Supplements',
    'Health & Wellness > Womens Health',
    'Hobbies & Interests > 3D Printing',
    'Hobbies & Interests > Antiquing & Collecting',
    'Hobbies & Interests > Astronomy & Stargazing',
    'Hobbies & Interests > Backpacking & Hiking',
    'Hobbies & Interests > Birdwatching',
    'Hobbies & Interests > Boating & Sailing',
    'Hobbies & Interests > Camping & Outdoors',
    'Hobbies & Interests >Canoeing & Kayaking',
    'Hobbies & Interests > Cars & Automotive > Car Customization & Tuning',
    'Hobbies & Interests > Cars & Automotive > Classic Cars',
    'Hobbies & Interests > Cars & Automotive > Electric Vehicles',
    'Hobbies & Interests > Cars & Automotive > Motorsports (F1, NASCAR)',
    'Hobbies & Interests > Cars & Automotive > Off-roading & 4x4',
    'Hobbies & Interests > Cars & Automotive > Supercars & Hypercars',
    'Hobbies & Interests > Chess',
    'Hobbies & Interests > Couponing',
    'Hobbies & Interests > Drones & RC Vehicles',
    'Hobbies & Interests > Electronics & Gadgets',
    'Hobbies-& Interests > Extreme Sports',
    'Hobbies & Interests > Fishing',
    'Hobbies & Interests > Foraging',
    'Hobbies & Interests > Genealogy',
    'Hobbies & Interests > Geocaching',
    'Hobbies & Interests > Home Automation',
    'Hobbies & Interests > Hunting',
    'Hobbies & Interests > Knitting & Crochet',
    'Hobbies & Interests > Lockpicking',
    'Hobbies & Interests > Magic & Illusion',
    'Hobbies & Interests > Metal Detecting',
    'Hobbies & Interests > Model Building (Cars, Planes, etc.)',
    'Hobbies & Interests > Motorcycling',
    `Hobbies & Interests > Parkour & Freerunning`,
    'Hobbies & Interests > Pen & Paper RPGs (D&D)',
    'Hobbies & Interests > Poker & Card Games',
    'Hobbies & Interests > Quilting',
    'Hobbies & Interests > Radio & Ham Radio',
    'Hobbies & Interests > Scrapbooking',
    'Hobbies & Interests > Scuba Diving & Snorkeling',
    'Hobbies & Interests > Sewing',
    'Hobbies & Interests > Skateboarding & Longboarding',
    'Hobbies & Interests > Skiing & Snowboarding',
    'Hobbies & Interests > Stamp Collecting',
    'Hobbies & Interests > Surfing',
    'Hobbies & Interests > Survivalism & Prepping',
    'Hobbies & Interests > Train Spotting & Model Trains',
    'Hobbies & Interests > Traveling',
    'Hobbies & Interests > Urban Exploration',
    'Hobbies & Interests > Woodworking',
    'Movies & Television > Action & Adventure',
    'Movies & Television > Animation',
    'Movies & Television > Celebrities & Film Industry',
    'Movies & Television > Comedy',
    'Movies & Television > Documentaries',
    'Movies & Television > Drama',
    'Movies & Television > Film & TV Analysis',
    'Movies & Television > Film & TV History',
    'Movies & Television > Film & TV Production',
    'Movies & Television > Film & TV Reviews',
    'Movies & Television > Horror',
    'Movies & Television > Independent Film',
    'Movies & Television > Musicals',
s    'Movies & Television > Mystery & Crime',
    'Movies & Television > Reality TV',
    'Movies & Television > Romance',
    'Movies & Television > Science Fiction & Fantasy',
    'Movies & Television > Sitcoms',
    'Movies & Television > Soap Operas & Telenovelas',
    'Movies & Television > Streaming Services (Netflix, Hulu, etc.)',
    'Movies & Television > Talk Shows',
    'Movies & Television > TV Series & Shows',
    'Movies & Television > Voice Acting',
    'Music > A Cappella',
    'Music > Afrobeats',
    'Music > Ambient',
    'Music > Americana & Folk',
    'Music > Bluegrass',
    'Music > Blues',
    'Music > Bollywood & Indian Pop',
    'Music > Chiptune',
    'Music > Choral',
    'Music > Christian & Gospel',
    'Music > Classical',
    'Music > Country',
    'Music > Cover Songs',
    'Music > Dance & Electronic',
    'Music > Disco',
    'Music > Drum and Bass',
    'Music > Dubstep',
    'Music > EDM',
    'Music > Emo',
    'Music > Funk',
    'Music > Grunge',
    'Music > Hardcore',
    'Music > Heavy Metal',
    'Music > Hip Hop & Rap',
    'Music > House',
    'Music > Indie & Alternative',
    'Music > Industrial',
    'Music > Instrumental',
    'Music > J-Pop',
    'Music > Jazz',
    'Music > K-Pop',
    'Music > Latin',
    'Music > Lo-fi',
    'Music > Marching Bands',
    'Music > Music Composition & Theory',
    'Music > Music Festivals',
    'Music > Music History',
    'Music > Music Industry',
    'Music > Music Production & DJing',
    'Music > Music Videos',
    'Music > Musical Instruments > Brass',
    'Music > Musical Instruments > Drums & Percussion',
    'Music > Musical Instruments > Guitar & Bass',
    'Music > Musical Instruments > Keyboard & Piano',
    'Music > Musical Instruments > Strings',
    'Music > Musical Instruments > Woodwinds',
    'Music > Musicals & Show Tunes',
    'Music > New Wave',
    'Music > Opera',
    'Music > Parody & Comedy Music',
    'Music > Pop',
    'Music > Psychedelic Rock',
    'Music > Punk',
    'Music > R&B & Soul',
    'Music > Reggae & Dancehall',
    'Music > Rock',
    'Music > Ska',
    'Music > Synthwave',
    'Music > Techno',
    'Music > Trance',
    'Music > Trap',
    'Music > Turntablism',
    'Music > Vaporwave',
    'Music > World Music',
    'News & Politics > Activism & Protests',
    'News & Politics > Conservative Politics',
    'News & Politics > Conspiracies',
    'News & Politics > Elections',
    'News & Politics > Environmental Issues',
    'News & Politics > Fact-Checking & Media Literacy',
    'News & Politics > Geopolitics',
    'News & Politics > Government & Public Administration',
    'News & Politics > Human Rights',
    'News & Politics > International News',
    'News & Politics > Investigative Journalism',
    'News & Politics > Law & Legal System',
    'News & Politics > Leftist & Progressive Politics',
    'News & Politics > Libertarian Politics',
    'News & Politics > Local News',
    'News & Politics > Military & Defense',
    'News & Politics > Political Cartoons & Satire',
    'News & Politics > Political Commentary',
    'News & Politics > Political History',
    'News & Politics > Political Scandals',
    'News & Politics > Political Science',
    'News & Politics > Social Justice',
    'News & Politics > True Crime',
    'News & Politics > US Politics',
    'News & Politics > World News',
    'Podcasts & Radio > Comedy Podcasts',
    'Podcasts & Radio > Educational Podcasts',
    'Podcasts & Radio > News & Politics Podcasts',
s    'Podcasts & Radio > Radio Broadcasting',
    'Podcasts & Radio > Society & Culture Podcasts',
    'Podcasts & Radio > Sports Podcasts',
    'Podcasts & Radio > Storytelling Podcasts',
    'Podcasts & Radio > Technology Podcasts',
    'Podcasts & Radio > True Crime Podcasts',
    'Science & Technology > Aerospace & Aviation',
    'Science & Technology > Agriculture & AgTech',
    'Science & Technology > Anthropology',
    'Science & Technology > Archaeology',
    'Science & Technology > Artificial Intelligence > AI Art & Music',
    'Science & Technology > Artificial Intelligence > AI Ethics',
    'Science & Technology > Artificial Intelligence > Large Language Models (LLMs)',
    'Science & Technology > Artificial Intelligence > Machine Learning',
    'Science & Technology > Artificial Intelligence > Natural Language Processing (NLP)',
    'Science & Technology > Astronomy & Space Exploration',
    'Science & Technology > Augmented & Virtual Reality (AR/VR)',
    'Science & Technology > Automation & Robotics',
    'Science & Technology > Big Data',
    'Science & Technology > Bioinformatics',
    'Science & Technology > Biology',
    'Science & Technology > Biotechnology',
    'Science & Technology > Blockchain & Web3',
    'Science & Technology > Chemistry',
d    'Science & Technology > Citizen Science',
    'Science & Technology > Climate Science',
    'Science & Technology > Cloud Computing',
    'Science & Technology > Cognitive Science',
    'Science & Technology > Computer Hardware > Custom PCs & Modding',
    'Science & Technology > Computer Hardware > CPUs & GPUs',
    'Science & Technology > Computer Hardware > Keyboards & Peripherals',
    'Science & Technology > Computer Science',
    'Science & Technology > Cybersecurity & Hacking',
    'Science & Technology > Data Science',
    'Science & Technology > Earth Sciences (Geology, Oceanography)',
    'Science & Technology > Ecology & Conservation',
    'Science & Technology > Electrical Engineering',
    'Science & Technology > Energy & Renewables',
    'Science & Technology > Engineering (General)',
    'Science & Technology > Environmental Science',
    'Science & Technology > Forensics',
    'Science & Technology > Futurism & Transhumanism',
    'Science & Technology > Genetics & Genomics',
s    'Science & Technology > GIS & Cartography',
    'Science & Technology > History of Science & Tech',
    'Science & Technology > Information Technology (IT)',
    'Science & Technology > Internet Culture & Memes',
    'Science & Technology > Internet of Things (IoT)',
    'Science & Technology > Linguistics',
    'Science & Technology > Materials Science',
    'Science & Technology > Mathematics',
    'Science & Technology > Mechanical Engineering',
    'Science & Technology > Memes & Internet Culture',
    'Science & Technology > Mobile Development (iOS, Android)',
    'Science & Technology > Nanotechnology',
    'Science & Technology > Neuroscience',
    'Science & Technology > Open Source',
    'Science & Technology > Paleontology',
    'Science & Technology > Physics',
    'Science & Technology > Privacy & Encryption',
    'Science & Technology > Product & Industrial Design',
    'Science & Technology > Programming & Software Development > Agile & Scrum',
    'Science & Technology > Programming & Software Development > Algorithms & Data Structures',
    'Science & Technology > Programming & Software Development > APIs & Microservices',
    'Science & Technology > Programming & Software Development > C & C++',
    'Science & Technology > Programming & Software Development > C# & .NET',
    'Science & Technology > Programming & Software Development > Compilers & Interpreters',
    'Science & Technology > Programming & Software Development > DevOps',
    'Science & Technology > Programming & Software Development > Functional Programming',
    'Science & Technology > Programming & Software Development > Go (Golang)',
    'Science & Technology > Programming & Software Development > Java',
    'Science & Technology > Programming & Software Development > JavaScript & TypeScript',
    'Science & Technology > Programming & Software Development > Kotlin',
    'Science & Technology > Programming & Software Development > No-Code & Low-Code',
    'Science & Technology > Programming & Software Development > PHP',
    'Science & Technology > Programming & Software Development > Python',
    'Science & Technology > Programming & Software Development > Ruby',
    'Science & Technology > Programming & Software Development > Rust',
    'Science & Technology > Programming & Software Development > Swift & iOS Development',
    'Science & Technology > Programming & Software Development > Web Development > Backend',
    'Science & Technology > Programming & Software Development > Web Development > CSS & Frameworks',
    'Science & Technology > Programming & Software Development > Web Development > Frontend & React',
    'Science & Technology > Programming & Software Development > Web Development > HTML5',
    'Science & Technology > Quantum Computing',
    'Science & Technology > Science Communication',
    'Science & Technology > Social Media & Platforms',
    'Science & Technology > Sociology',
    'Science & Technology > Space Technology',
    'Science & Technology > Startups & Tech Industry',
    'Science & Technology > Transportation Tech',
    'Science & Technology > Video & Audio Technology',
    'Science & Technology > Wearable Tech',
    'Science & Technology > Zoology',
    'Sports > Action Sports',
    'Sports > American Football (NFL)',
    'Sports > Archery',
    'Sports > Australian Rules Football',
    'Sports > Badminton',
    'Sports > Baseball (MLB)',
    'Sports > Basketball (NBA)',
    'Sports > Billiards & Pool',
    'Sports > Bodybuilding & Fitness Competitions',
    'Sports > Bowling',
    'Sports > Boxing',
    'Sports > Cheerleading',
    'Sports > Climbing',
    'Sports > Cricket',
    'Sports > Cycling',
    'Sports > Darts',
    'Sports > Disc Golf',
    'Sports > Diving',
    'Sports > Dodgeball',
    'Sports > Equestrian',
    'Sports > Fencing',
    'Sports > Fantasy Sports',
    'Sports > Field Hockey',
    'Sports > Figure Skating',
    'Sports > Fishing',
    'Sports > Golf',
    'Sports > Gymnastics',
    'Sports > Handball',
    'Sports > Hockey (NHL)',
    'Sports > Horse Racing',
    'Sports > Lacrosse',
    'Sports > Martial Arts (MMA, UFC)',
    'Sports > Olympics',
    'Sports > Paintball & Airsoft',
    'Sports > Paralympics',
s    'Sports > Pickleball',
    'Sports > Pro Wrestling (WWE, AEW)',
    'Sports > Racquetball',
    'Sports > Roller Derby',
    'Sports > Rowing',
    'Sports > Rugby',
    'Sports > Running & Track',
    'Sports > Sailing',
    'Sports > Skateboarding',
    'Sports > Skiing & Snowboarding',
    'Sports > Soccer (Football)',
    'Sports > Softball',
    'Sports > Sports Betting',
    'Sports > Sports Broadcasting & Journalism',
    'Sports > Sports History',
    'Sports > Sports Management & Business',
    'Sports > Sports Medicine',
    'Sports > Sports Psychology',
s    'Sports > Squash',
    'Sports > Surfing',
    'Sports > Swimming',
    'Sports > Table Tennis',
    'Sports > Tennis',
    'Sports > Ultimate Frisbee',
    'Sports > Volleyball',
    'Sports > Water Polo',
    'Sports > Weightlifting',
    'Sports > Winter Sports',
    'Sports > Wrestling',
];
